spring:
  application:
    name:
      backend

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://192.168.20.40:3306/hotel_management
    username: cuongdso
    password: Pcuong@2411

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false