spring:
  application:
    name:
      backend

  datasource:
    url: jdbc:mysql://localhost:3306/hotel_management
    username: root
    password: 27102005

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
